### ISSUE TITLE
[WebUI] blazor?

### ISSUE THREAD

**Issue by GeorgeS2019** [LittleLittleCloud/StepWise#40]
It is a limitation for .NET community that we do not have a workflow UI that everyone can use **completely** based on blazor instead of the more common javascript/typecript frameworks.

I will come back with more links how blazor could be used for Workflow UI

**Comment by AmjedKhaled165** [comment]
try this

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by GeorgeS2019** [comment]
https://github.com/elsa-workflows/elsa-studio/discussions/10#discussioncomment-9931553

**Comment by GeorgeS2019** [comment]
Please share screenshot, the link to archive.

**Comment by LittleLittleCloud** [comment]
Thanks, I'm more familiar with typescript in frontend and I am still prototyping the UI, so in the current stage I prefer using typescript + react to construct the frontend UI.

If you plan to prototype some UI using blazor feel free to give a try. We provides the complete openapi scheme [here](https://github.com/LittleLittleCloud/StepWise/tree/main/schema) for the backend api
