### ISSUE TITLE
@minhhut

### ISSUE THREAD

**Issue by Happy444666** [LittleLittleCloud/StepWise#93]
@minhhut 

> I find the project very interesting by its minimalist design and concept! Looking forward to the next release 👍

Thanks for the feedback

> Does this one include ability to access running/existing workflow by ID? Currently, if I refresh the UI page, it starts a new workflow while I want to continue with the previous running workflow.

The reload and continue from previous checkpoint is not the topic for this thread, but that's something really useful and is on stepwise's radar (at least on my radar) to implement for next release

_Originally posted by @LittleLittleCloud in https://github.com/LittleLittleCloud/StepWise/issues/82#issuecomment-2411749939_

**Comment by LittleLittleCloud** [comment]
@Happy444666 ?
